### ISSUE TITLE
Value of type 'AuthDataResult' has no member 'providerID'

### ISSUE THREAD

**Issue by WilliamLoke** [vinothvino42/Chit-Chat#1]
tried to run the project but met with this error at AuthService class

**Comment by vinothvino42** [comment]
Can you please send me a screenshot of AuthService class ?

**Comment by vinothvino42** [comment]
In **Firebase v5.0.0** - Added `FIRAuthDataResultCallback`, which returns an **AuthDataResult object** instead of a **User object** after sign-in. This replaces `FIRAuthResultCallback` for the following methods: `signInWithEmail:`, `signInwithCredential:`, `signInAnonymouslyWithCompletion:`, and `createUserWithEmail:`. See this [Firebase iOS Release Notes](https://firebase.google.com/support/release-notes/ios#5.2.0) for more information. Now I updated the repository. Check it out @WilliamLoke
